### ISSUE TITLE
Wondering why system:admin is not allowed to do the install

### ISSUE THREAD

**Issue by maleck13** [redhat-developer/codeready-workspaces-deprecated#13]
Hey

Wondering what the reason behind not allowing a system:admin to do the install? The deploy script fails if it cannot get a token but doesn't seem to actually use that token afterwards?
https://github.com/redhat-developer/codeready-workspaces-deprecated/blob/master/operator-installer/deploy.sh#L123

**Comment by nickboldt** [comment]
CRW 1.2 is EOL. Please use CRW 2.0 and crwctl CLI application instead of this deprecated bash script.
