### ISSUE TITLE
Unable to deploy application due to unable to pull image

### ISSUE THREAD

**Issue by kshirsagarg** [redhat-developer/codeready-workspaces-deprecated#32]
Unable to deploy application due to unable to pull image with 1.2 version deploying on rhel 7 master Openshift cluster. Hence have edited deploy.sh for server_image veriable as RHEL7 and operator-rhel7:1.2, but still getting below error.

[root@devopenshift-master-0 files]# oc logs deployment/codeready-operator -n codeready
Error from server (BadRequest): container "codeready-operator" in pod "codeready-operator-7547984678-dnxpd" is waiting to start: ContainerCreating

**Comment by kshirsagarg** [comment]
I have tried with latest version 1.2.1 as well, but while execution of deploy.sh script getting below error and unable to pull image. Please suggest to fix this issue.

[INFO]: Creating cluster role binding to let operator service account create oAuthClients
[INFO]: Creating custom resource definition
[INFO]: Creating Operator Deployment
[INFO]: Waiting for the deployment/codeready-operator to be scaled to 1. Timeout 300 seconds
[ERROR]: Deployment timeout. Aborting.
[ERROR]: Check deployment logs and events:
[ERROR]: oc logs deployment/codeready-operator -n coderexecution6
[ERROR]: oc get events -n coderexecution6
-----------------------------------------------------------------------------------------------------
# oc logs deployment/codeready-operator -n coderexecution6
Error from server (BadRequest): container "codeready-operator" in pod "codeready-operator-7547984678-7n5l7" is waiting to start: trying and failing to pull image

**Comment by rhopp** [comment]
Hi @kshirsagarg 
Currently, default operator image is set to registry.redhat.io/codeready-workspaces/server-operator-rhel8:1.2. The registry `registry.redhat.io` requires authentication. Could you check if your cluster is able to pull from that registry? If not, please refer to the Codeready Workspaces documentation, section about installation - https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/1.2/html/administration_guide/installing_codeready-workspaces 
There is an "important" part in "Software requirements" section about how to make this work ;-)

**Comment by nickboldt** [comment]
No response from reporter after >8 months, so closing. 

I'll assume once the reporter authenticated w/ the repo, all was well.
