### ISSUE TITLE
deploy.sh fails on custom resource

### ISSUE THREAD

**Issue by pb82** [redhat-developer/codeready-workspaces-deprecated#49]
Running deploy.sh fails because [custom-resource.yaml](https://github.com/redhat-developer/codeready-workspaces-deprecated/blob/2.0.0.GA/operator-installer/custom-resource.yaml) is expected to be a template: https://github.com/redhat-developer/codeready-workspaces-deprecated/blob/2.0.0.GA/operator-installer/deploy.sh#L582

This seems to have changed in 2.0.0.GA, custom-resource.yaml is no longer a template.

**Comment by nickboldt** [comment]
If you're using deploy.sh for CRW 1.2, then get it and custom resource yaml ere:

https://github.com/redhat-developer/codeready-workspaces-deprecated/tree/1.2.2.GA/operator-installer

If you're deploying CRW 2.x, use crwctl or install via Operator Hub inside OCP/OSD.

https://github.com/redhat-developer/codeready-workspaces-chectl/tree/master/docs

Please note that new issues for CRW or crwctl should be opened here:

https://issues.redhat.com/browse/CRW
